### ISSUE TITLE
Incorrect behaviour of switch node - shows output state regardless of indicator setting.

### ISSUE THREAD

**Issue by BeenThereScrewedUp** [node-red/node-red-dashboard#506]
### What are the steps to reproduce?
Use a switch node in dashboard version 2.15.3. Do not connect the output.
Set "indicator" to "Switch icon shows the state of the input".
In the dashboard click the switch node.

### What happens?
The switch toggles.

### What do you expect to happen?
Nothing. This was the case until version 2.15.1
As the nodes output is not connected and the input does not change the switch should continue to show the state of the last input message.

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.15.3
- [x] Node-RED version: 0.20.5
- [x] node.js version: 8.16.0
- [x] npm version: 6.4.1
- [x] Platform/OS: Raspbian Stretch
- [x] Browser: Firefox 67

**Comment by dceejay** [comment]
Closed by 1de24484f391a9869bc15a185e58a5ded1fcecd7
release 2.15.4

**Comment by keptenkurk** [comment]
I think this change is plain wrong!
1. Why would the dashboard switch be inhibited when the switch icon shows the state of the input? 
2. Why would a switch have input states and output states? To me a switch only has one state
3. If "msg arrives on input, pass through to output" is checked, 2 messages will be output: one as received on the input and one from the switch itself even when there is no state change.

The way i have been using ui_switch so far is without passthrough using the input to sync its state with the real world and its output to control the real world. 
Please enlighten me...

**Comment by dceejay** [comment]
In passthru mode
   toggling the input - toggles the output and the icon follows the state of the switch
In non-passthru mode
   the indicator icon can show either the state of the input - or output
   if set to output - it will track the state when you click the switch in the ui. (basically the input from the flow will be ignored) 
   if set to input - it will track the state of the input to the node and not change when you click the switch. When you click the switch the node output will change - this can then be used to trigger some other part of the flow and then feed back into the input - for example to show that the result of the switch has actually turned something on.

There is a small bug in there still (now fixed in master) such that the icon still follows the input even if set to not passthru and track output.

**Comment by keptenkurk** [comment]
Currently in 2.15.4 in non passthru mode clicking the icon doesn't toggle the switch state (regardless of showing input or output state). Reverted to 2.13.0 to fix the project.

**Comment by keptenkurk** [comment]
[{"id":"13ccef1d.f45fd5","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"adc31b97.054d78","type":"ui_switch","z":"13ccef1d.f45fd5","name":"","label":"switch","tooltip":"","group":"44682755.b569d8","order":0,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":330,"y":120,"wires":[["60942476.bcd60c"]]},{"id":"60942476.bcd60c","type":"debug","z":"13ccef1d.f45fd5","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":570,"y":120,"wires":[]},{"id":"1a5d6804.a74bf8","type":"inject","z":"13ccef1d.f45fd5","name":"true","topic":"true","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":120,"wires":[["adc31b97.054d78","7966179c.f21728"]]},{"id":"3deb4cf4.ddefa4","type":"inject","z":"13ccef1d.f45fd5","name":"false","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":160,"wires":[["adc31b97.054d78","7966179c.f21728"]]},{"id":"7966179c.f21728","type":"ui_switch","z":"13ccef1d.f45fd5","name":"","label":"switch2","tooltip":"","group":"44682755.b569d8","order":1,"width":0,"height":0,"passthru":false,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"fa-eye","oncolor":"red","offvalue":"false","offvalueType":"bool","officon":"fa-eye","offcolor":"green","x":340,"y":180,"wires":[["60942476.bcd60c"]]},{"id":"44682755.b569d8","type":"ui_group","z":"","name":"Default","tab":"c867c88f.8930c8","disp":true,"width":"6","collapse":false},{"id":"c867c88f.8930c8","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]``

**Comment by dceejay** [comment]
closed by - 42ebfeec1f2c6c410d17a09b0593676538a96ab2

**Comment by keptenkurk** [comment]
sorry to bug you again Dave. In non-passthru and showing output it's now indeed possible to click and toggle the switch. Thanks for the quick solution!
 However i still don't get the request of @BeenThereScrewedUp to inhibit toggling the switch when showing input state. But that could be just me...
I might need to rework my projects to set ui_switches to passthru and avoid loops by inhibiting the outging msg some other way to still be able to use 2.14 and beyond (if the above request truly makes sense)

**Comment by dceejay** [comment]
He's asking for it to work as it did before and as I described above. Which it now does.
think of it as a switch and an indicator... the indicator can either be connected direct to the switch - which tells you that you have pushed the switch - but you don't actually know that what is connected downstream has done what you told it - by connecting the indicator to the input (but disabling passthru) -you can apply that feedback - so when click on - something happens and then the lamp goes on to confirm. The switch (when clicked in the UI side - is still switching (and can be seen in debug) - but the indicator won't show it.

**Comment by wongnam** [comment]
> sorry to bug you again Dave. In non-passthru and showing output it's now indeed possible to click and toggle the switch. Thanks for the quick solution!
> However i still don't get the request of @BeenThereScrewedUp to inhibit toggling the switch when showing input state. But that could be just me...
> I might need to rework my projects to set ui_switches to passthru and avoid loops by inhibiting the outging msg some other way to still be able to use 2.14 and beyond (if the above request truly makes sense)

@keptenkurk Actually, the Ui-Switch node is working very smoothly and perfectly in version 2.15.4. I think there is no need to make any changes in the particular case you are experiencing.

Your problem is very easy to handle. It's now in "non-passthru and showing output" so you can use dummy function node to loop the state output to the input of ui-switch node in this case.

Hope it helps you and everyone.

### The sample flow as below:
`
[{"id":"c95be12e.86f1f","type":"ui_switch","z":"dceadd9d.ba53c","name":"","label":"switch","tooltip":"","group":"bd4c84d3.a8f078","order":2,"width":0,"height":0,"passthru":false,"decouple":"false","topic":"","style":"","onvalue":"ON","onvalueType":"str","onicon":"","oncolor":"","offvalue":"OFF","offvalueType":"str","officon":"","offcolor":"","x":370,"y":1450,"wires":[["786537f4.2a0f98","243097ba.da0d08"]]},{"id":"48efac7a.d9ac84","type":"inject","z":"dceadd9d.ba53c","name":"","topic":"","payload":"ON","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":1430,"wires":[["c95be12e.86f1f"]]},{"id":"786537f4.2a0f98","type":"debug","z":"dceadd9d.ba53c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":610,"y":1450,"wires":[]},{"id":"dadd3f6f.c1955","type":"inject","z":"dceadd9d.ba53c","name":"","topic":"","payload":"OFF","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":1480,"wires":[["c95be12e.86f1f"]]},{"id":"243097ba.da0d08","type":"function","z":"dceadd9d.ba53c","name":"feedback","func":"\nreturn msg;","outputs":1,"noerr":0,"x":370,"y":1390,"wires":[["c95be12e.86f1f"]]},{"id":"bd4c84d3.a8f078","type":"ui_group","z":"","name":"Testing SW/Button","tab":"71576856.c06de8","order":2,"disp":true,"width":"6","collapse":false},{"id":"71576856.c06de8","type":"ui_tab","z":"","name":"Testing","icon":"fa-edit","order":7}]
`

**Comment by wongnam** [comment]
update, 2.15.4 Yes, when "non-passthru" select "show state of out" put, there is no effect when pressing it on the dashboard. If this issue was fixed then ignore this information of me. thanks

![image](https://user-images.githubusercontent.com/36041520/59080474-161e9e00-8913-11e9-8d1d-393b8e68f9c7.png)
