### ISSUE TITLE
Dashboard UI stopped working with webhookrelay.com service

### ISSUE THREAD

**Issue by midnight1979** [node-red/node-red-dashboard#683]
### What are the steps to reproduce?
1. Try to open web interface of dashboard http://blynkapi.webrelay.io/ui

### What happens?
Interface is not opening. In crhome console having messages:
WebSocket connection to 'ws://blynkapi.webrelay.io/ui/socket.io/?EIO=3&transport=websocket&sid=knbN_sp5uVLu0bnTAAAH' failed: WebSocket is closed before the connection is established.

### What do you expect to happen?
version 2.19.2 works well. After update to latest version 2.28.1 UI is not working with webhookrelay.com service.

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.28.1
- [x] Node-RED version: 1.2.9
- [x] node.js version: 12.20.2
- [x] npm version: 6.14.11
- [x] Platform/OS: Arm linux (RPI4)
- [x] Browser: Google Crhome

**Comment by midnight1979** [comment]
i little addition - Node Red web interface ok working!

**Comment by dceejay** [comment]
have you endured you have flushed the browser cache after the upgrade ?

**Comment by midnight1979** [comment]
Yes of course, i'm also tried to downgrade dashboard version to 2.19.2 and it is working.

**Comment by midnight1979** [comment]
I think that there was some changes of socket lib (module) of dashboard in newer versions and something goes wrong )

**Comment by midnight1979** [comment]
And as I said earlier- node-red web interface is working well!

**Comment by dceejay** [comment]
Nothing has changed there as far as I know. The socket.io is pinned back as we haven’t dropped node8 in core yet so it is as it was previously.

**Comment by midnight1979** [comment]
So, then I don't know why it doesn't working on versions newer 2.19.2, I can try to install next several versions to "catch" the first one where this error is present. But not having free time right now for this tests.

**Comment by dceejay** [comment]
Ah sorry - 2.19.1 is while back so yes something may have changed (now at 2.28...) - Goggling around it does seem like there are a lot of people with this on socket.io - the core doesn't use it which may explain why it works.

**Comment by midnight1979** [comment]
So, how this problem can be solved?

**Comment by dceejay** [comment]
good question - lots of hits on browser extensions causing it. Also some on https connections. Did you try a different browser ? incognito mode ? 
the whole point of socket.io is that it tries different connection types websocket, polling etc and if one fails then it tries another - so one failure should not cause a complete stop.

**Comment by midnight1979** [comment]
I can't use public static ip for my node red dashboard due to technical restrictions - that's why I'm using tunneling with webrelay.io that worked perfect before dashboard update. But also want stay up to date with dashboard package, can you help me with this problem, I'm also understand that not so lot of people is in my situation, but I think that I'm not alone - maybe other don't saying about this and still using 2.19...

**Comment by midnight1979** [comment]
> Did you try a different browser ? incognito mode ?
Yes I did - Microsoft edge, incognito mode in Google Chrome - no success...

**Comment by midnight1979** [comment]
Links that I wrote are my current test links - you can try to open them and will see how do they work (not work ))

**Comment by dceejay** [comment]
I have pushed a version to master where I pin back socket.io to level that was in use in 2.19 - you can try it by installing manually
```
cd ~/.node-red
npm i node-red/node-red-dashboard
```

**Comment by midnight1979** [comment]
IT IS WORKING NOW!!!! THANKS A LOT!!!!

**Comment by midnight1979** [comment]
npm i node-red/node-red-dashboard - hangs on "rollbackFailedOptional: verb..."

**Comment by dceejay** [comment]
not sure if that's now working or not for you... I have seen that when installing direct from github it takes forever but should eventually install. If it's working it may only be temporary fix - as come April when we drop support for node8 and 10 we will bump to socket.io v4 to get latest security fixes... and it may break again - but no doubt you can let us know :-)

**Comment by midnight1979** [comment]
no - it still don't working... just now installed manually and no effect ((

**Comment by midnight1979** [comment]
just now tryed to install different versions of dashboard and my problem is beginning from 2.23.0 version.
working well on 2.22.1

**Comment by dceejay** [comment]
Ok - another possible fix pushed :-)...
This removes a check for direct websocket connection... which should never really happen as it should always be an upgrade from an http connection - but we will see.

**Comment by midnight1979** [comment]
no - it is not helped (((

**Comment by midnight1979** [comment]
io.use(function (socket, next) {
             if (socket.client.conn.request.url.indexOf("transport=websocket") !== -1) {
                 // Reject direct websocket requests
                 socket.client.conn.close();
                 return;
             }
            next();
            //if (socket.handshake.xdomain === false) {
            //    return next();
            //} else {
            //    socket.disconnect(true);
            //}
        });
    }

THATS WORKING!!!!

**Comment by dceejay** [comment]
so yeah - that proxy is of course acting as a cross domain forwarder. So in the general case that is not something we want to allow as it's just bad security so I will need to make it optional for cases such as yours.

**Comment by dceejay** [comment]
Aha - actually the answer is right there... :-) If you declare  your own middleware then I won't do that check - so in your settings.js just set
```
ui: { middleware: function (req, res, next) { next() } },
```
should do it.

**Comment by midnight1979** [comment]
ok, i'll try to do this!

**Comment by midnight1979** [comment]
just tryed - it is not working!

**Comment by midnight1979** [comment]
is seems like ui.js does not see this parameter from settings.js

**Comment by dceejay** [comment]
try adding a `console.log("Hi");` just before the `next()` - so you can check if it's being called.
(you need to restart Node-RED for it to take effect.) You can see where it should be being checked about 10 lines above the io.use you edited above.

**Comment by midnight1979** [comment]
middleware is calling - i'm getting log messages.

**Comment by midnight1979** [comment]
Welcome to Node-RED
===================

17 Feb 00:21:29 - [info] Node-RED version: v1.2.9
17 Feb 00:21:29 - [info] Node.js  version: v12.20.2
17 Feb 00:21:29 - [info] Linux 5.10.11-v7l+ arm LE
17 Feb 00:21:30 - [info] Loading palette nodes
UIS { path: 'ui', middleware: [Function: middleware] }
17 Feb 00:21:31 - [info] Dashboard version 2.28.1 started at /ui
17 Feb 00:21:31 - [info] Settings file  : /home/pi/.node-red/settings.js
17 Feb 00:21:31 - [info] Context store  : 'default' [module=memory]
17 Feb 00:21:31 - [info] User directory : /home/pi/.node-red

**Comment by midnight1979** [comment]
17 Feb 00:22:47 - [info] Starting flows
17 Feb 00:22:47 - [info] Started flows
17 Feb 00:22:47 - [info] Server now running at http://127.0.0.1:1880/
17 Feb 00:22:47 - [info] serial port /dev/ttyS0 opened at 57600 baud 8N1
Hi!
Hi!
Hi!
Hi!
Hi!
Hi!
Hi!
Hi!
Hi!

**Comment by midnight1979** [comment]
something wrong with conditional sentences... because:
if (socket.handshake.xdomain === false) { return next(); }
                else { socket.disconnect(true); log.info("i'm still here!"); }
still calling

**Comment by midnight1979** [comment]
what is the setting allowCrossDomain and where is it???

**Comment by midnight1979** [comment]
ui: { path: 'ui', allowCrossDomain: true, middleware: function (req, res, next) {
            // Do something more interesting here.
            // console.log('Hi!')
            next()
        }
    },

THATS WORKING!

**Comment by midnight1979** [comment]
Welcome to Node-RED
===================

17 Feb 00:39:00 - [info] Node-RED version: v1.2.9
17 Feb 00:39:00 - [info] Node.js  version: v12.20.2
17 Feb 00:39:00 - [info] Linux 5.10.11-v7l+ arm LE
17 Feb 00:39:01 - [info] Loading palette nodes
UIS {
  path: 'ui',
  allowCrossDomain: true,
  middleware: [Function: middleware]
}
17 Feb 00:39:02 - [info] Dashboard version 2.28.1 started at /ui
17 Feb 00:39:02 - [info] Settings file  : /home/pi/.node-red/settings.js
17 Feb 00:39:02 - [info] Context store  : 'default' [module=memory]
17 Feb 00:39:02 - [info] User directory : /home/pi/.node-red

**Comment by midnight1979** [comment]
Now everything works fine. Will these changes be included in the next release?

**Comment by dceejay** [comment]
allowCrossDomain is not needed - just using your own middleware should be enough. That was always there.

**Comment by midnight1979** [comment]
But it doesn't working without allowCrossDomain = true.

if (socket.handshake.xdomain === false) { return next(); }
else { socket.disconnect(true); log.info("i'm still here!"); }

**Comment by midnight1979** [comment]
typeof uiSettings.ioMiddleware is undefined - is it normal?

**Comment by midnight1979** [comment]
due to thease conditions it always will go to the last else statment, because uiSettings.ioMiddleware is undefined and ioMiddleware is not Array, thats why it goes to check allowCrossDomain and etc... with socket.disconnect(true)

    if (typeof uiSettings.ioMiddleware === "function") {
        io.use(uiSettings.ioMiddleware);
    }
    else if (Array.isArray(uiSettings.ioMiddleware)) {
        uiSettings.ioMiddleware.forEach(function(ioMiddleware) {
            io.use(ioMiddleware);
        });
    }
    else {

**Comment by dceejay** [comment]
sorry - I was reading the variable name wrong... should be  ioMiddleware that is defined of course...
so just
```
ui: { ioMiddleware: function (req, res, next) { next() } },

```

**Comment by midnight1979** [comment]
i can check it in the evening.

**Comment by midnight1979** [comment]
i tryed to do this yesterday - having errors:
17 Feb 16:16:30 - TypeError: next is not a function
    at Array.ioMiddleware (/home/pi/.node-red/settings.js:112:54)
    at run (/home/pi/.node-red/node_modules/socket.io/lib/namespace.js:124:11)
    at Namespace.run (/home/pi/.node-red/node_modules/socket.io/lib/namespace.js:136:3)
    at Namespace.add (/home/pi/.node-red/node_modules/socket.io/lib/namespace.js:164:8)
    at Client.doConnect (/home/pi/.node-red/node_modules/socket.io/lib/client.js:97:20)
    at Client.connect (/home/pi/.node-red/node_modules/socket.io/lib/client.js:66:17)
    at Server.onconnection (/home/pi/.node-red/node_modules/socket.io/lib/index.js:435:10)
    at Server.emit (events.js:314:20)
    at Server.handshake (/home/pi/.node-red/node_modules/engine.io/lib/server.js:342:8)
    at /home/pi/.node-red/node_modules/engine.io/lib/server.js:230:12

**Comment by midnight1979** [comment]
maybe some mistake in function arguments???

**Comment by midnight1979** [comment]
Thats working:

    ui: { ioMiddleware: function (req, next) {  next() } },

**Comment by midnight1979** [comment]
It would be great to include this moment to the dashboard  caption maybe...

**Comment by midnight1979** [comment]
and i think we can close this issue

**Comment by dceejay** [comment]
I'll update the default settings file to include some words. Thanks for being patient.
